Cole db
CSC207-2022F-UofT/course-project-team-gordon-ramsey pull request #36
Opened 2022-12-05 19:42 UTC by ColePurboo

updated UserDb (addUser, validateUser etc)

2022-12-05 19:45 UTC, jaylovegood approved these changes, later dismissed
Looks great and ready to merge!

2022-12-05 21:30 UTC, jaylovegood approved these changes, later dismissed
Looks good!
I'm not sure how the DB interface works rn but would it be possible to make UserDB implement DB as well?

2022-12-05 21:30 UTC, jaylovegood commented on src/main/java/business/rules/dbs/UserDB.java
> +public class UserDB implements Serializable {
wouldn't it be better to make it implement DB as well?

2022-12-06 02:50 UTC, alexfigner requested changes
I fixed the conflict in User. I echo Jisu's comment that UserDB should implement both Serializable and DB, since they are interfaces and can do so.

2022-12-06 02:59 UTC, alexfigner approved these changes
Great work - thanks for making the change to UserDB.

2022-12-06 02:59 UTC, merged